spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 500MB
server:
  port: 18080


file:
  qiniu:
    AccessKey: 5nem0zWsGig_lE-SOmIAJz84cQz9vEB8vQJGJvHy
    SK: RFleqgTYUZULFzhzViB_GRJFcnmUMDdxJtEM2V2V
