spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://localhost:3306/db_jyb_test?Unicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 18080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: org.cn.jiangzhe.*

